[package]
name = "crystal-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui.workspace = true
crossterm.workspace = true
vt100.workspace = true
anyhow.workspace = true
crystal-config = { path = "../crystal-config" }
crystal-terminal = { path = "../crystal-terminal" }
