[package]
name = "kubetile-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
portable-pty.workspace = true
tokio.workspace = true
crossterm.workspace = true
anyhow.workspace = true
tracing.workspace = true
vt100.workspace = true
ratatui.workspace = true
